#CICD workflow for the K8s multi tier app

name: CICD workflow for the K8s multitier app
on:
  push:
    branches:
      - feature-branch

  schedule:
    - cron: '12 * * * 1-5'

  workflow_dispatch:

#permission: read

jobs:
  BUILD:
    runs-on: ubuntu-server
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      
      - name: Install Maven
        run: mvn Install

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vprofile-app
          path: target/*.war

      - name: notify if fails
        if: failure()
        run: "echo build failed and for more information check logs!"

  TESTING:
    runs-on: ubuntu-server
    needs: BUILD
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      
      - name: maven Test
        run: mvn test

      - name: maven checkstyle
        run: mvn checkstyle:checkstyle

      - name: notify if fails
        run: "echo echo build failed and for more information check logs!"