#Building a workflow pipeline for this multi tier project

name: K8S multitier workflow

on:
  push:
    branches:
      - main

    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/main.yaml'
  
  schedule:
    - cron: '12 * * * *'

  workflow_dispatch:

jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: Install Maven
        run: mvn install

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vprofile-app
          path: target/*.war

      - name: Notify if build fails
        if: failure()
        run: echo "Build Job failed! Please check logs for the details"

  Testing:
    runs-on: ubuntu-latest
    needs: BUILD
    steps:
      - name: code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vprofile-app
      - name: Run tests
        run: mvn test
      - name: checkstyle
        run: mvn checkstyle:checkstyle

      - name: Notify if test fails
        if: failure()
        run: echo "Test Job failed! Please check logs for the details"

  Security_Scan:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
      - name: code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-path: '.'
          severity-threshold: 'CRITICAL'
          format: 'json'
          exit-code: '0'
          vulnerability-type: 'os,library'
          output: 'trivy-report.json'

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json

  Deploy:
    environment: prod
    runs-on: ubuntu-latest
    needs: Security_Scan
    steps:
      - name: code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vprofile-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/vprofile-app:latest 
        
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/vprofile-app:latest
          severity-threshold: 'CRITICAL'
          format: 'json'
          exit-code: '1'

      - name: Notify if deployment fails
        if: failure()
        run: echo "Deployment Job failed! Please check logs for the details"